<?php

namespace Database\Seeders;

use App\Models\Inventario;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class InventarioSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = now();
        /*$invReales = [
             ['1109-03','Activímetro','Descripcion de ejemplo','ACT 15 PF','ALFANUCLEAR']
            ,['413','Arco C','Descripcion de ejemplo','BV Endura','Philips']
            ,['No registra','Aspirador Portatil','Descripcion de ejemplo','H003-A','Folee']
            ,['124110002','Aspirador Portatil','Descripcion de ejemplo','','Mediair']
            ,['URA-061767','Autoclave','Descripcion de ejemplo','533HC','Getinge']
            ,['16695','Autoclave','Descripcion de ejemplo','HS6610','Getinge']
            ,['103895','Autoclave','Descripcion de ejemplo','HR10052','Oppici']
            ,['5700004173631','Balanza Analítica','Descripcion de ejemplo','700','SECA']
            ,['56700112100647','Balanza Analítica','Descripcion de ejemplo','700','SECA']
            ,['5,70011E+12','Balanza Analítica','Descripcion de ejemplo','220','SECA']
            ,['4020024586','Balanza Analítica','Descripcion de ejemplo','Professional','Health O meter']
            ,['5700026105375','Balanza Analítica','Descripcion de ejemplo','700','SECA']
            ,['171524201725','Balanza Analítica','Descripcion de ejemplo','700','SECA']
            ,['5700201161547','Balanza Analítica','Descripcion de ejemplo','700','SECA']
            ,['No registra','Balanza Analítica','Descripcion de ejemplo','No registra','Health O meter']
            ,['5700191138898','Balanza Analítica','Descripcion de ejemplo','No registra','SECA']
            ,['No registra','Balanza Analítica','Descripcion de ejemplo','No registra','SECA']
            ,['','Balanza digital (mide tambien)','Descripcion de ejemplo','EBST-20','Facultad de farmacia uv']
            ,['53740081030680','Balanza Electrónica','Descripcion de ejemplo','374','SECA']
            ,['13081406','Balanza Electrónica','Descripcion de ejemplo','M11260','ADE']
            ,['5,37401E+12','Balanza Electrónica','Descripcion de ejemplo','3741321009','SECA']
            ,['RS042B328','Fuente de Luz','Descripcion de ejemplo','PS2-HP','Fujinon']
            ,['1030230','Balanza Electrónica','Descripcion de ejemplo','986','Excell']
            ,['5374198130427','Balanza Electrónica','Descripcion de ejemplo','374','SECA']
            ,['1595','Baño maria chico','Descripcion de ejemplo','','Amilab']
            ,['1014920','Baño maria grande','Descripcion de ejemplo','DH4','Helmer']
            ,['1595','Baño Termoregulado','Descripcion de ejemplo','No registra','AMILAB']
            ,['18111096313','Base Computador Mamógrafo','Descripcion de ejemplo','Lorad M IV','Hologic']
            ,['131217202931','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['070625011782','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,5111E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,00521E+11','Base Humidificadora','Descripcion de ejemplo','HC-150','Fisher&Paykel']
            ,['FBFE00139','Oximetro de pulso','Descripcion de ejemplo','3800','Datex-Ohmeda']
            ,['1,00505E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,10506E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1V327A059','Procesador de Endoscopia','Descripcion de ejemplo','Eve E 200','Fujinon']
            ,['1,10818E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,10314E+11','Base Humidificadora','Descripcion de ejemplo','MR 810','Fisher&Paykel']
            ,['1,10506E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,5111E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,00505E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['19680878','Base primea','Descripcion de ejemplo','Base primea sp','Fresenius Kabi']
            ,['1,40708E+11','Base Humidificadora','Descripcion de ejemplo','MR 850','Fisher&Paykel']
            ,['1,10314E+11','Base Humidificadora','Descripcion de ejemplo','MR 810','Fisher&Paykel']
            ,['1,8011E+11','Base Humidificadora','Descripcion de ejemplo','MR 810','Fisher&Paykel']
            ,['23108753','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108749','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108750','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108751','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108752','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108754','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['21938622','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938289','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['20165818','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['20374790','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938291','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['19747467','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['20165813','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['23108755','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108756','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['0128801-04','Autoclave','Descripcion de ejemplo','Amsco Century v116','Steris']
            ,['0128801-01','Autoclave','Descripcion de ejemplo','Amsco Century v120','Steris']
            ,['23108757','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108758','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['19922071','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['','Lavadora descontaminadora','Descripcion de ejemplo','WD14','']
            ,['EPC040265039F','Lavadora Ultrasónica','Descripcion de ejemplo','No registra','No registra']
            ,['20165819','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938288','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938292','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938293','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['20374790','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938622','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['21938290','Bomba Alimentación','Descripcion de ejemplo','Applix Smart','Fresenius Kabi']
            ,['23108760','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108761','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108762','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108763','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108764','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23553149','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23553150','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23553151','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23553152','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23553153','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['23108759','Bomba Alimentación','Descripcion de ejemplo','Amika Es','Fresenius Kabi']
            ,['','Bomba Alimentación ','Descripcion de ejemplo','faltaa box 5','Fresenius Kabi']
            ,['MD038844-H6','Monitor de Signos Vitales','Descripcion de ejemplo','Duo','Datascope']
            ,['39837','Monitor de Signos Vitales','Descripcion de ejemplo','Duo','Datascope']
            ,['19926998','Bomba Anestesia','Descripcion de ejemplo','Pilot  2SP','Fresenius Kabi']
            ,['17284852','Bomba Anestesia','Descripcion de ejemplo','Pilot  2SP','Fresenius Kabi']
            ,['17315898','Bomba Anestesia','Descripcion de ejemplo','Pilot  2SP','Fresenius Kabi']
            ,['19354408','Bomba Anestesia','Descripcion de ejemplo','Pilot Delta SP','Fresenius Kabi']
            ,['800410557','Bomba Anestesia','Descripcion de ejemplo','Alaris','Tiva']
            ,['17585259','Bomba Anestesia','Descripcion de ejemplo','Pilot Anesthesie 2 SP','Fresenius Kabi']
            ,['081380-19680878','Bomba Anestesia','Descripcion de ejemplo','Base primea sp','Fresenius Kabi']
            ,['081380-21454431','Bomba Anestesia','Descripcion de ejemplo','Base primea sp','Fresenius Kabi']
            ,['081380-19327567','Bomba Anestesia','Descripcion de ejemplo','Base primea sp','Fresenius Kabi']
            ,['081380-21152746','Bomba Anestesia','Descripcion de ejemplo','Base primea sp','Fresenius Kabi']
            ,['No registra','Lavachatas','Descripcion de ejemplo','No registra','Oppici']
            ,['082381-18755549','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-21156783','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-21451908','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-21451907','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-19537186','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-21156782','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-19145180','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['082381-19537190','Bomba Anestesia','Descripcion de ejemplo','Module DPS Orchestra SP2','Fresenius Kabi']
            ,['17584419','Bomba Anestesia','Descripcion de ejemplo','Pilot  2SP','Fresenius Kabi']
            ,['18691675','Bomba Anestesia','Descripcion de ejemplo','Pilot  2SP','Fresenius Kabi']
            ,['10992','Detector de radioactividad','Descripcion de ejemplo','GS1','GAMASCOUT']
            ,['21622520','Bomba de Irrigacion','Descripcion de ejemplo','OFP-2','Olympus']
            ,['21851116','Bomba de Irrigacion','Descripcion de ejemplo','OFP-2','Olympus']
            ,['P00486','Bomba de Irrigacion','Descripcion de ejemplo','EGA-500','Endo Stratus']
            ,['No registra','Bomba de Lavado','Descripcion de ejemplo','No registra','No registra']
            ,['016-173939-02','Bomba de Vacío','Descripcion de ejemplo','LEMA50AZ','Flowserve']
            ,['22980646','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981670','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981630','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981668','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254469','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980644','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981641','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254474','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981625','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['18299076','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299080','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299087','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299093','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299096','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299101','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299103','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299135','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299233','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299261','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299266','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299270','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299659','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299783','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['22981658','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981635','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254484','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981623','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980636','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981663','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981624','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980637','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981654','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981627','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980623','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980630','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23017845','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254477','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981665','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980635','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981631','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980649','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254476','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980641','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981636','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254479','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981646','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981640','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981639','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981638','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981626','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981649','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980633','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980645','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254466','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254478','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981651','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981634','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981637','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980624','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['19327199','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19357505','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19357533','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19502282','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19770402','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19835259','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19835260','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['18299133','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299257','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299264','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299267','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299619','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299648','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['23254470','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981653','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981667','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981655','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980627','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['18299078','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299094','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299209','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['19835262','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['20370056','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['20370055','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19296354','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19835258','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['18299271','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299283','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299764','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['19770449','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19533050','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19533074','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['22980626','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254475','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981622','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980629','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254472','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980643','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981648','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981659','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254483','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981666','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['A53144-C7','Monitor de Signos Vitales','Descripcion de ejemplo','Acuttor Plus','Datascope']
            ,['MD06970-K7','Monitor de Signos Vitales','Descripcion de ejemplo','Duo','Datascope']
            ,['22981643','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981656','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980651','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980650','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254467','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980632','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981664','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981669','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981650','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254471','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980648','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254482','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981644','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980628','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['18199108','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18298000','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299092','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299124','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299173','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299232','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299238','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299243','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299259','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299262','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299265','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299272','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299738','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299782','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299758','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299080','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299271','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299701','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299267','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299754','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299109','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299186','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299589','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299254','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299260','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['22980642','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254468','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981633','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980639','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','Fanem']
            ,['23254480','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['20257555','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19471326','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['19449447','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['18299081','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299105','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299107','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299167','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299589','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299695','Bomba Infusión','Descripcion de ejemplo','Plum A+ ','Hospira']
            ,['18299772','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299229','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['18299751','Bomba Infusión','Descripcion de ejemplo','Plum A+',' Hospira']
            ,['23643788','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980647','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980640','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981652','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981629','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['HCC50016','Cuna Radiante','Descripcion de ejemplo','No registra','Ohmeda']
            ,['22981628','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981647','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981621','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981632','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981645','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981657','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254481','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23254465','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980625','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981662','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981660','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980634','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22980631','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['22981661','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643776','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643777','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643778','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643779','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643780','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643781','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643782','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643783','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643784','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643785','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643786','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['SDT08490038SP','Monitor de Signos Vitales','Descripcion de ejemplo','Dinamap V100','GE']
            ,['23643787','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643789','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643790','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643791','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643792','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643793','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['19835280','Bomba Infusión','Descripcion de ejemplo','Optima MS','Fresenius Kabi']
            ,['21211223','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21577042','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['19741620','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['19805494','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905803','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905804','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905805','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905806','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905802','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905807','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905809','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905811','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905812','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905813','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905815','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905816','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905814','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['21905808','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia','Fresenius Kabi']
            ,['MD06970-K7','Monitor NIBP','Descripcion de ejemplo','Duo','Datascope']
            ,['19537186','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['19537190','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['18755547','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['21156782','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['21156783','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['21451907','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['15519','Bomba jeringa','Descripcion de ejemplo','PERFUSOR COMPACT','BRAUN']
            ,['18755549','Bomba jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Vial']
            ,['21451908','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['18755549','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['19145180','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Vial']
            ,['20493056','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['17100350','Bomba Jeringa','Descripcion de ejemplo','MVP SM  IS','Fresenius Kabi']
            ,['20461449','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461450','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['19145180','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20493055','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20461448','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['18457534','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['19145174','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20109197','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20109198','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20109201','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20280084','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20493083','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20646121','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20493082','Bomba Jeringa','Descripcion de ejemplo','Orchestra SP2','Fresenius Kabi']
            ,['20461453','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461454','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461455','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461456','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461457','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461458','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461459','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['20461460','Bomba Jeringa','Descripcion de ejemplo','MVP SM  SP','Fresenius Kabi']
            ,['19741621','Bomba Jeringa','Descripcion de ejemplo','Injectomat agilia sp','Fresenius Kabi']
            ,['23644346','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644347','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644348','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644349','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644350','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644351','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['19741626','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21577039','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635894','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635895','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635896','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635897','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635898','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635899','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635900','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21635901','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905044','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905047','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905048','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21619435','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['19805529','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905045','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905046','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21577038','Bomba Jeringa','Descripcion de ejemplo','Injectomat Agilia SP2','Fresenius Kabi']
            ,['21905049','Bomba Jeringa','Descripcion de ejemplo','','Fresenius Kabi']
            ,['23644341','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644340','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644342','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644343','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644344','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['23644345','Bomba Jeringa','Descripcion de ejemplo','Injectomat MC Agilia ','Fresenius Kabi']
            ,['NX4128RE','Bomba para Artroscopia','Descripcion de ejemplo','Continuous Wave III Arthroscopy Pump','Arthrex']
            ,['21905807','Calefactor Radiante','Descripcion de ejemplo','IW920AEU','Fisher&Paykel']
            ,['57008','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['57008','Calentador de paciente','Descripcion de ejemplo','750','Bair Hugger']
            ,['56542','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['57006','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['57001','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['57003','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['10477','Calentador de Paciente','Descripcion de ejemplo','750','Bair - Hugger']
            ,['38530','Calentador de Paciente','Descripcion de ejemplo','505','Bair - Hugger']
            ,['73346','Calentador de Paciente','Descripcion de ejemplo','775','Bair - Hugger']
            ,['73345','Calentador de Paciente','Descripcion de ejemplo','775','Bair - Hugger']
            ,['R28727','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28728','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28732','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28733','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28734','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28740','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28743','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28751','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28756','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28760','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28773','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28776','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28777','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54524','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54632','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54634','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54639','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54646','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54650','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28757','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54626','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54644','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54636','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28770','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28767','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28730','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28731','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28737','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28738','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28739','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28741','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28746','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28747','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['ON 089634','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['ON 089637','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['ON004789','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['AR001551','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['ON014511','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['ON 004781','Lámpara Quirurgica','Descripcion de ejemplo','No registra','ALM']
            ,['ON089638','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['ON089642','Lámpara Quirurgica','Descripcion de ejemplo','PrismaLix','ALM']
            ,['R28748','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28752','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28753','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28755','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['A003-A5-0010','Mesa Quirúrgica','Descripcion de ejemplo','NOT5600S','Trident']
            ,['A003-A5-0088','Mesa Quirúrgica','Descripcion de ejemplo','NOT5600S','Trident']
            ,['A003-A6-0006','Mesa Quirúrgica','Descripcion de ejemplo','NOT5600S','Trident']
            ,['R28757','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['A003-A5-0001','Mesa Quirúrgica','Descripcion de ejemplo','NOT5600S','Trident']
            ,['R28758','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28759','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28762','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28764','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['','Mesa Quirúrgica','Descripcion de ejemplo','Alphamax','Maquet']
            ,['R28766','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28767','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28768','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28769','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28770','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28771','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28772','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28774','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28775','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54546','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54626','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54627','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54628','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54630','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54631','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54633','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54635','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54636','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54640','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54642','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54643','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54644','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54645','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54647','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54648','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54649','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28750','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28744','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28760','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54525','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28729','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54637','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28732','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28729','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28735','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28736','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28742','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28745','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28749','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28750','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28754','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['5700026105364','Balanza analítica','Descripcion de ejemplo','700','SECA']
            ,['R28763','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54547','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54638','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54711','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28746','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28764','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54642','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['800-12B-0182','Monitor de Signos Vitales','Descripcion de ejemplo','Pamo II plus MP800','MEK']
            ,['R28755','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['1302039880','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 035679','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039874','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039875','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039876','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039879','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['20034308','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['20034310','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['20034312','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['20034309','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['20034313','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['20034311','Cama Eléctrica','Descripcion de ejemplo','378200B','VIVO']
            ,['1009 031161','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1009 031156','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1009 031157','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1009 031158','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1009 031159','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1009 031160','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['R28744','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28761','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R28765','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54629','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54637','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['9371160946','Monitor de Signos Vitales','Descripcion de ejemplo','MD200A','IVMedical']
            ,['R54641','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['1302 039875','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039879','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039880','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['FBFE00140','Saturómetro','Descripcion de ejemplo','3800','Datex-Ohmeda']
            ,['FBFE00147','Saturómetro','Descripcion de ejemplo','3800','Datex-Ohmeda']
            ,['FBFE02351','Saturómetro','Descripcion de ejemplo','3800','Datex-Ohmeda']
            ,['1302 039877','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['1302 039876','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['R54633','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['2514569861','Monitor Multiparámetros','Descripcion de ejemplo','Infinity Vista','Dräger']
            ,['5513772465','Monitor Multiparámetros','Descripcion de ejemplo','Infinity Vista','Dräger']
            ,['6004477266','Monitor Multiparámetros','Descripcion de ejemplo','Inifinity Delta','Dräger']
            ,['6004477667','Monitor Multiparámetros','Descripcion de ejemplo','Inifinity Delta','Dräger']
            ,['1302 039878','Cama Eléctrica','Descripcion de ejemplo','Epic II','Stryker']
            ,['R28774','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['R54647','Cama Eléctrica','Descripcion de ejemplo','FL28','Stryker']
            ,['1404030026','Camilla de Parto','Descripcion de ejemplo','4701','Stryker']
            ,['0807 107176','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['1010 031433','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['0807 107177','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['1209 035444','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035445','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035449','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035450','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035451','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035448','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035446','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1010 031432','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209035442','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209035447','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209035445','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209035450','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040768','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040772','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040779','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040782','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040783','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040790','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040792','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040793','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1610038755','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040795','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040798','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040799','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1610038731','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1610038732','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1610038719','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1610038769','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1611040799','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['0807107179','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['0807 107174','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['0807 107175','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['1209 035442','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['0807 107177','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['0807107178','Camilla de Trasporte','Descripcion de ejemplo','0738','Stryker']
            ,['1209 035443','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['1209 035451','Camilla de Trasporte','Descripcion de ejemplo','0747','Stryker']
            ,['Generico','Camilla Genérica','Descripcion de ejemplo','','']
            ,['10H047314','Capturador de Video','Descripcion de ejemplo','SDC Ultra','Stryker']
            ,['14J034794','Capturador de Video','Descripcion de ejemplo','SDC3','Stryker']
            ,['10H047254','Capturador de Video','Descripcion de ejemplo','SDC Ultra','Stryker']
            ,['No registra','Carro de Paro','Descripcion de ejemplo','UNIKO','Malvestio']
            ,['No registra','Carro de Paro','Descripcion de ejemplo','UNIKO','Malvestio']
            ,['21905808','Carro de Paro','Descripcion de ejemplo','MX-34EMG','Bailida']
            ,['21905809','Carro de Paro','Descripcion de ejemplo','MX-34EMG','Bailida']
            ,['VM17-01369','Carro de Paro','Descripcion de ejemplo','MX34EMG','Bailida']
            ,['0100255','Monitor de Signos Vitales','Descripcion de ejemplo','Vismo','Nihon-Kohden']
            ,['1632','Carro de Paro','Descripcion de ejemplo','UNIKO','Malvestio']
            ,['No registra','Carro de yeso','Descripcion de ejemplo','No registra','No registra']
            ,['SN2518','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['SN2516','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['SN2515','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['SN2517','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['SN2512','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['SN2521','carro para instrumental','Descripcion de ejemplo','CARGO','MALVESTIO']
            ,['5330A00840','Central de Monitoreo','Descripcion de ejemplo','M3150','Philips']
            ,['C2C3356S11','Central de Monitoreo','Descripcion de ejemplo','CDA19','GE']
            ,['4946A07221','Central de monitoreo','Descripcion de ejemplo','M3150','Philips']
            ,['4825A06990','Central de Monitoreo','Descripcion de ejemplo','M3150','Philips']
            ,['5412A03456','Central de Monitoreo','Descripcion de ejemplo','M3150','Philips']
            ,['SN1205358','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['SN1205354','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['V1607436SX','Compresor Neumatico','Descripcion de ejemplo','SCD700 SERIES ','Kendall']
            ,['V1607433SX','Compresor Neumatico','Descripcion de ejemplo','SCD700 SERIES ','Kendall']
            ,['SN0907108','Compresor Neumatico','Descripcion de ejemplo','SCD Express','Kendall']
            ,['SN0919865','Compresor Neumatico','Descripcion de ejemplo','SCD Express','Kendall']
            ,['SN1018769','Compresor Neumatico','Descripcion de ejemplo','SCD Express','Kendall']
            ,['SN1209199','Compresor Neumatico','Descripcion de ejemplo','SCD Express','Kendall']
            ,['V1642543SX','Compresor Neumatico','Descripcion de ejemplo','SCD700 SERIES ','Kendall']
            ,['SN1209192','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['SN1205320','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['V1642679SX','Compresor Neumatico','Descripcion de ejemplo','SCD700 SERIES ','Kendall']
            ,['SN1209200','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['SN1209188','Compresor Neumatico','Descripcion de ejemplo','SCD express','Kendall']
            ,['10I007764','Consola de Cámara','Descripcion de ejemplo','1288HD','Stryker']
            ,['10I020394','Consola de Cámara','Descripcion de ejemplo','1288HD','Stryker']
            ,['14I030044','Consola de Cámara','Descripcion de ejemplo','1488HD','Stryker']
            ,['08F007414','Consola de Cámara','Descripcion de ejemplo','1088HD','Stryker']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','RN-5','ICR']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','FANEM']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','FANEM']
            ,['N11HT721210071','Ventilador Portatil','Descripcion de ejemplo','HT-70 Plus','Newport Medical']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','FANEM']
            ,['No registra','Cuna Básica','Descripcion de ejemplo','Bassinet Panda','FANEM']
            ,['F05404','Cuna con Barrotes','Descripcion de ejemplo','FL19F','Stryker']
            ,['F05436','Cuna con Barrotes','Descripcion de ejemplo','FL19F','Stryker']
            ,['F50739','Cuna con Barrotes','Descripcion de ejemplo','FL19F','Stryker']
            ,['ASEM-0005','Cuna Radiante','Descripcion de ejemplo','Babytherm 8004','Dräger']
            ,['ASEM-0004','Cuna Radiante','Descripcion de ejemplo','Babytherm 8004','Dräger']
            ,['WP03584','Cuna Radiante','Descripcion de ejemplo','Air- Shield Resucitare','Dräger']
            ,['DG06674','Cuna Radiante','Descripcion de ejemplo','Air- Shield Resucitare','Dräger']
            ,['WP03412/WP03418','Cuna Radiante','Descripcion de ejemplo','Air- Shield Resucitare','Dräger']
            ,['350826GA','Densitómetro','Descripcion de ejemplo','Lunar prodigy','GE']
            ,['1014920','Descongelador de plasma (37°)','Descripcion de ejemplo','DH4','HELMER']
            ,['1723','Desfibrilador','Descripcion de ejemplo','Cardiolife Tec-7511K','Nihon-Kohden']
            ,['AF13D028430','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF13D028433','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF13D028444','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF17E065938','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF12L026152','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['1058','Desfibrilador','Descripcion de ejemplo','Cardiolife Tec-5531E','Nihon-Kohden']
            ,['2151','Desfibrilador','Descripcion de ejemplo','Cardiolife Tec-5531E','Nihon-Kohden']
            ,['50C01769C','Digitalizador de RX','Descripcion de ejemplo','Horizon DICOM Printer','Codonics']
            ,['AF14J041086','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF13D028427','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['910','Desfibrilador','Descripcion de ejemplo','Cardiolife Tec-5521E','Nihon-Kohden']
            ,['2152','Desfibrilador','Descripcion de ejemplo','Cardiolife Tec-5531E','Nihon-Kohden']
            ,['M16100220028','Detector cardiofetal','Descripcion de ejemplo','','EDAN']
            ,['M16100220029','Detector cardiofetal','Descripcion de ejemplo','','EDAN']
            ,['CTS-5554','Detector latidos fetales','Descripcion de ejemplo','Sonicaid 421','Oxford']
            ,['CTS-5563','Detector latidos fetales','Descripcion de ejemplo','Sonicaid 421','Oxford']
            ,['30109','Digitalizador de RX','Descripcion de ejemplo','CR30-X','AGFA']
            ,['No registra','Digitalizador de RX','Descripcion de ejemplo','DX-M','AGFA']
            ,['1111229995','electrobisturi','Descripcion de ejemplo','GEN11','ethicon']
            ,['02BTNH','Ecotomógrafo','Descripcion de ejemplo','HDI 5000 Somo CT','Philips']
            ,['B0G9F3','Ecotomógrafo','Descripcion de ejemplo','IU-22','Philips']
            ,['B0MC9F','Ecotomógrafo','Descripcion de ejemplo','IU-22','Philips']
            ,['US90922788','Ecotomógrafo','Descripcion de ejemplo','HD 15','Philips']
            ,['A31170','Ecotomógrafo','Descripcion de ejemplo','Voluson 730 PRO','GE']
            ,['WK1YG5','Ecotomógrafo','Descripcion de ejemplo','Edge','Sonosite']
            ,['B000129','Electrobisturi','Descripcion de ejemplo','ESG-100','Olympus']
            ,['B000146','Electrobisturi','Descripcion de ejemplo','ESG-100','Olympus']
            ,['S3D08582AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['S3D08584AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['FBFE02352','Saturómetro','Descripcion de ejemplo','3800','Datex-Ohmeda']
            ,['S3D08589AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['S3D08593AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['S3D08682AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['F1B4920B','Electrobisturí','Descripcion de ejemplo','Force EZ','Valleylab']
            ,['S3D08594AX','Electrobisturí','Descripcion de ejemplo','Force FX','Valleylab']
            ,['T8D6441E','Electrobisturí','Descripcion de ejemplo','ForceTriad','Valleylab']
            ,['114280220613','Electrocardiógrafo','Descripcion de ejemplo','ELI 250C','Mortara']
            ,['113299164954','Electrocardiógrafo','Descripcion de ejemplo','ELI 150C','Mortara']
            ,['500001428','Electrocardiógrafo','Descripcion de ejemplo','Marquett Mac 500','GE']
            ,['113200164956','Electrocardiógrafo','Descripcion de ejemplo','ELI 150c','Mortara']
            ,['1,132E+11','Electrocardiógrafo','Descripcion de ejemplo','ELI 10','Mortara']
            ,['SEA232310C1354D','Electrocardiógrafo','Descripcion de ejemplo','SE-601B','Edan']
            ,['112200117457','Electrocardiógrafo','Descripcion de ejemplo','ELI 250C','Mortara']
            ,['113299164955','Electrocardiógrafo','Descripcion de ejemplo','ELI 150C','Mortara']
            ,['1,1429E+11','Electrocardiógrafo','Descripcion de ejemplo','ELI 150C','Mortara']
            ,['ZX4807','Endoscopio','Descripcion de ejemplo','8402ZX','Karl Storz']
            ,['VW1766','Endoscopio','Descripcion de ejemplo','20701020','Karl Storz']
            ,['11P034816','Endoscopio','Descripcion de ejemplo','Endovision XL 202800 20','Karl Storz']
            ,['VW2532','Endoscopio','Descripcion de ejemplo','AQZ ','Karl Storz']
            ,['EI1266','Endoscopio (fuente de luz)','Descripcion de ejemplo','hamou mycro-hysteroflator 264315 20','Karl Storz']
            ,['NV384A005','Endosonografo','Descripcion de ejemplo','Sonoprobe System RS702','Fujinon']
            ,['1111229995','Equipo de artroscopia','Descripcion de ejemplo','Endo surgery Generator','Ethicon']
            ,['1111512115','Equipo de artroscopia','Descripcion de ejemplo','Endo surgery Generator','Ethicon']
            ,['PA12878','Equipo de dialisis','Descripcion de ejemplo','PrismaFlex','GAMBRO']
            ,['7148363','Equipo de Electrocirugia','Descripcion de ejemplo','UES-40','Olympus']
            ,['ARWK-0031','Fototerapia','Descripcion de ejemplo','PT-4000','Dräger']
            ,['ARWL-0048','Fototerapia','Descripcion de ejemplo','PT-4000','Dräger']
            ,['ASEA-0002','Fototerapia','Descripcion de ejemplo','PT-4000','Dräger']
            ,['ASEJ-0023','Fototerapia','Descripcion de ejemplo','PT-4000','Dräger']
            ,['1S095A044','Fuente de Luz','Descripcion de ejemplo','XL4450HD','Fujinon']
            ,['1S095A043','Fuente de Luz','Descripcion de ejemplo','XL4450HD','Fujinon']
            ,['1S095A307','Fuente de Luz','Descripcion de ejemplo','XL4450HD','Fujinon']
            ,['12G049984','Fuente de Luz','Descripcion de ejemplo','L9000','Stryker']
            ,['81C00631C','Grabadora','Descripcion de ejemplo','Virtua Xr','Codonics']
            ,['72C00234C','Grabadora','Descripcion de ejemplo','Virtua Xr','Codonics']
            ,['10H029254','Fuente de Luz','Descripcion de ejemplo','L9000','Stryker']
            ,['15A033354','Fuente de Luz','Descripcion de ejemplo','L9000','Stryker']
            ,['WX1314','Fuente de Luz','Descripcion de ejemplo','LEDnova 20161120','Storz']
            ,['15A016904','Fuente de Luz','Descripcion de ejemplo','L9000','Stryker']
            ,['7671645','Fuente de luz ','Descripcion de ejemplo','EXERA III CLV-190','Olympus']
            ,['7777431','Fuente de luz ','Descripcion de ejemplo','EXERA III CLV-190','Olympus']
            ,['7168424','Fuente de luz del fibrobroncoscopio','Descripcion de ejemplo','CLK-4','OLYMPUS']
            ,['GN4108440','Generador','Descripcion de ejemplo','Endo-Surgery Generator','Ethicon']
            ,['20124316AR3','Generador RF','Descripcion de ejemplo','RFG2','Vnus']
            ,['8517678062','Hemoglucotest','Descripcion de ejemplo','Performa','Accu-check']
            ,['111-3-01912','Hipo/Hipertermia','Descripcion de ejemplo','Blaketrol III','Cincinatti Sub Zero']
            ,['6210','Impresora de Placas','Descripcion de ejemplo','Drystar 5302','AGFA']
            ,['GB26461','Incubadora','Descripcion de ejemplo','Isolette C2000','Dräger']
            ,['2176U1109R','INFILTRATION PUMP','Descripcion de ejemplo','TPMP-01','VNUS']
            ,['QT17540','Incubadora','Descripcion de ejemplo','Isolette C2000','Dräger']
            ,['WP14352','Incubadora','Descripcion de ejemplo','Isolette C2000','Dräger']
            ,['CU03969','Incubadora','Descripcion de ejemplo','Isolette 8000','Dräger']
            ,['CU03970','Incubadora','Descripcion de ejemplo','Isolette 8000','Dräger']
            ,['CU03971','Incubadora','Descripcion de ejemplo','Isolette 8000','Dräger']
            ,['FB01696','Incubadora de transporte','Descripcion de ejemplo','Globetrotter TI-500','Dräger']
            ,['WP04971','Incubadora de transporte','Descripcion de ejemplo','TI500','Dräger']
            ,['3585','Infiltrador','Descripcion de ejemplo','PSITEC III','Byron Medical']
            ,['620-040-504-F12','Insuflador','Descripcion de ejemplo','Pneumo sure','Stryker']
            ,['620-040-503-F12','Insuflador','Descripcion de ejemplo','Pneumo sure','Stryker']
            ,['1310CE447','Insuflador','Descripcion de ejemplo','Pneumo sure','Stryker']
            ,['1008CE154','Insuflador','Descripcion de ejemplo','Pneumo sure','Stryker']
            ,['7631518','Insuflador CO2','Descripcion de ejemplo','VCR','Olympus']
            ,['44100','Lampara Halogena','Descripcion de ejemplo','Lucea 40','Maquet']
            ,['AR01','Lampara Halogena','Descripcion de ejemplo','Lucea 40','Maquet']
            ,['AR010378','Lampara Halogena','Descripcion de ejemplo','Lucea 40','Maquet']
            ,['AR020055','Lámpara Halogena','Descripcion de ejemplo','Lucea 50','Maquet']
            ,['AR010378','Lámpara Halógena','Descripcion de ejemplo','Marquett','GE']
            ,['No registra','Lámpara Halógena','Descripcion de ejemplo','No registra','Welch Allyn']
            ,['MV10A1C312315C2230','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16A1C312315C2231','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV10A1C312315C2226','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16A1C312315C2227','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16B14201313C0752','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16B14201313C0753','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16A1C312315C2229','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['MV16A1C312315C2228','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['','Lámpara Quirurgica','Descripcion de ejemplo','marLED','KLS Martin']
            ,['WP00284','Lámpara Radiante','Descripcion de ejemplo','Air- Shield Resucitare','Dräger']
            ,['11215','Máquina de Anestesia','Descripcion de ejemplo','Fabius CE','Dräger']
            ,['ASDB-0037','Máquina de Anestesia','Descripcion de ejemplo','Fabius GS Premiun','Dräger']
            ,['ASEL-0248','Máquina de Anestesia','Descripcion de ejemplo','Primus IE','Dräger']
            ,['ASDB-0036','Máquina de Anestesia','Descripcion de ejemplo','Fabius GS Premiun','Dräger']
            ,['ASEL-0188','Máquina de Anestesia','Descripcion de ejemplo','Primus IE','Dräger']
            ,['ASEL-0189','Máquina de Anestesia','Descripcion de ejemplo','Primus IE','Dräger']
            ,['ASJL-0314','Máquina de Anestesia','Descripcion de ejemplo','Primus IE','Dräger']
            ,['ASJL-0301','Máquina de Anestesia','Descripcion de ejemplo','Primus IE','Dräger']
            ,['ARZH-0001','Máquina de Anestesia MRI','Descripcion de ejemplo','Fabius','Dräger']
            ,['SEW13338274HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SEW13338264HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SEW13338273HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SEW13338266HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SEW13338271HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SEW13338272HA','Monitor Multiparámetros','Descripcion de ejemplo',' B650','GE']
            ,['SGF13227257WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13217114WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227190WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227250WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227252WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227277WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227269WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['VG000862','Monitor Multiparámetros','Descripcion de ejemplo','Vigilance II','Edward Lifesciences']
            ,['DE50867582','Monitor Multiparámetros','Descripcion de ejemplo','MX800','Philips']
            ,['DE50867593','Monitor Multiparámetros','Descripcion de ejemplo','MX800','Philips']
            ,['DE50867603','Monitor Multiparámetros','Descripcion de ejemplo','MX800','Philips']
            ,['DE50867610','Monitor Multiparámetros','Descripcion de ejemplo','MX800','Philips']
            ,['DE50867612','Monitor Multiparámetros','Descripcion de ejemplo','MX800','Philips']
            ,['DE82018855','Monitor Multiparámetros','Descripcion de ejemplo','Mp40 ','Philips']
            ,['DE82018860','Monitor Multiparámetros','Descripcion de ejemplo','Mp40 ','Philips']
            ,['DE82018866','Monitor Multiparámetros','Descripcion de ejemplo','Mp40 ','Philips']
            ,['DE82020145','Monitor Multiparámetros','Descripcion de ejemplo','Mp40 ','Philips']
            ,['DE84315802','Monitor Multiparámetros','Descripcion de ejemplo','MP60','Philips']
            ,['DE82057106','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['DE82057108','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['DE82057113','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['DE82057134','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['DE82057141','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['DE82057153','Monitor Multiparámetros','Descripcion de ejemplo','MP50','Philips']
            ,['SGF15131141WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SGF13227194WA','Monitor Multiparámetros','Descripcion de ejemplo','B20','GE']
            ,['SK416491224HA','Monitor Multiparámetros','Descripcion de ejemplo','B650','GE']
            ,['DE12517584','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE12517585','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE12517586','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE12517587','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE12517589','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE12517583','Monitor Multiparámetros','Descripcion de ejemplo','Mx700','Philips']
            ,['DE58551496','Monitor Multiparámetros','Descripcion de ejemplo','MX700','Philips']
            ,['DE58551622','Monitor Multiparámetros','Descripcion de ejemplo','MX700','Philips']
            ,['DE58551629','Monitor Multiparámetros','Descripcion de ejemplo','MX700','Philips']
            ,['DE58551637','Monitor Multiparámetros','Descripcion de ejemplo','MX700','Philips']
            ,['DE58551641','Monitor Multiparámetros','Descripcion de ejemplo','MX700','Philips']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['','Set diagnostico mural','Descripcion de ejemplo','','Welch Allyn']
            ,['N/A','Set laringoscopio curvo','Descripcion de ejemplo','','Welch Allyn']
            ,['N/A','Set laringoscopio recto','Descripcion de ejemplo','','Welch Allyn']
            ,['ref 408282 lot 16319','Set ostetoscopio movil','Descripcion de ejemplo','Generico','Generico']
            ,['174832','Set Oxímetro de pulso','Descripcion de ejemplo','RADICAL 7','Masimo']
            ,['0611000429','Sierra cortayeso','Descripcion de ejemplo','841','Stryker']
            ,['A366004','Torre de iriigacion','Descripcion de ejemplo','EASY IRRIGATION TOWER','ALLEN']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','89P','Malvestio']
            ,['','Sillon','Descripcion de ejemplo','898','Malvestio']
            ,['ASEN 0021','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0022','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0023','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0024','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0025','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0026','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0027','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['ASEN 0028','Unidad de soporte de techo','Descripcion de ejemplo','AGILA','Dräger']
            ,['VCOK03597','Unidad de Terapia V.A.C','Descripcion de ejemplo','InfoV.A.C.','KCI']
            ,['VCOK04905','Unidad de Terapia V.A.C','Descripcion de ejemplo','InfoV.A.C.','KCI']
            ,['55190','Ventilador de Alta Frecuencia','Descripcion de ejemplo','5000','SLE']
            ,['BBW01025','Ventilador de Alta Frecuencia','Descripcion de ejemplo','3100A','Sensor Medics']
            ,['AJV02270','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['ASDM-0054','Ventilador Mecánico','Descripcion de ejemplo','VN-500','Dräger']
            ,['ASEK-0060','Ventilador Mecánico','Descripcion de ejemplo','VN-500','Dräger']
            ,['3501051473','Ventilador Mecánico','Descripcion de ejemplo','NPB 760','Puritan Benet']
            ,['BHV01343','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['AFV02498','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['AJT06079','Ventilador Mecánico','Descripcion de ejemplo','Vela','Carefusion Viasys']
            ,['BFV05474','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['AEV02516','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['BAV06521','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['BBV01591','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['BAV06531','Ventilador Mecánico','Descripcion de ejemplo','AVEA','Carefusion Viasys']
            ,['H001795391','Ventilador no invasivo','Descripcion de ejemplo','Bipap Auto Serie M','RESPIRONICS']
            ,['TV017111409','Ventilador no invasivo','Descripcion de ejemplo','Trilogy ','Philips']
            ,['TV01601270D','Ventilador no invasivo','Descripcion de ejemplo','Trilogy ','Philips']
            ,['ZX4807','Videoendoscopio','Descripcion de ejemplo','8402ZX','STORZ']
            ,['6002409','Ventilador no invasivo','Descripcion de ejemplo','BIPAP Synchrony L.A','RESPIRONICS']
            ,['6002668','Ventilador no invasivo','Descripcion de ejemplo','BIPAP Synchrony L.A','RESPIRONICS']
            ,['TV014110705','Ventilador no invasivo','Descripcion de ejemplo','Trilogy 202','Philips']
            ,['TV016091204','Ventilador no invasivo','Descripcion de ejemplo','Trilogy 202','Philips']
            ,['1V568A076','Video Procesador','Descripcion de ejemplo','VP-4450HD','Fujinon']
            ,['1V568A077','Video Procesador','Descripcion de ejemplo','VP-4450HD','Fujinon']
            ,['1V568A950','Video Procesador','Descripcion de ejemplo','VP-4450HD','Fujinon']
            ,['7634286','Video Procesador','Descripcion de ejemplo','EVIS EXERA III','Olympus']
            ,['7740373','Video Procesador','Descripcion de ejemplo','EVIS EXERA III','Olympus']
            ,['2823096','Videocolenoscopio','Descripcion de ejemplo','GIF-H170L','Olympus']
            ,['2612033','Videocolonoscopio','Descripcion de ejemplo','CF-H170','Olympus']
            ,['3C559A172','Videocolonoscopio','Descripcion de ejemplo','EC-590ZW/L','Fujinon']
            ,['3C592A216','Videocolonoscopio','Descripcion de ejemplo','EC-530WL','Fujinon']
            ,['3C592A218','Videocolonoscopio','Descripcion de ejemplo','EC-530WL','Fujinon']
            ,['3C657A159','Videocolonoscopio','Descripcion de ejemplo','EC-530LP','Fujinon']
            ,['2823147','Videocolonoscopio','Descripcion de ejemplo','CF-H170','Olympus']
            ,['2714962','Videopanendoscopio','Descripcion de ejemplo','GIF-H170','Olympus']
            ,['3G349A224','Videopanendoscopio','Descripcion de ejemplo','EG-590ZW','Fujinon']
            ,['6G247A006','Videopanendoscopio','Descripcion de ejemplo','EG-590ZW','Fujinon']
            ,['3G361A633','Videopanendoscopio','Descripcion de ejemplo','EG-530WR','Fujinon']
            ,['3G361A634','Videopanendoscopio','Descripcion de ejemplo','EG-530WR','Fujinon']
            ,['4G374A021','Videopanendoscopio','Descripcion de ejemplo','EG-530FP','Fujinon']
            ,['3G376A077','Videopanendoscopio','Descripcion de ejemplo','EG-530D','Fujinon']
            ,['5D102A010','Videopanendoscopio','Descripcion de ejemplo','ED-530XT','Fujinon']
            ,['SD102A008','Videopanendoscopio','Descripcion de ejemplo','EC-530XT','Fujinon']
            ,['5D102A009','Videopanendoscopio','Descripcion de ejemplo','EC-530XT','Fujinon']
            ,['2826877','Videopanendoscopio','Descripcion de ejemplo','GIF-H170','Olympus']
            ,['2714968','Videopanendoscopio','Descripcion de ejemplo','GIF-H170','Olympus']
            ,['WSX181016-268','Armario de endoscopia','Descripcion de ejemplo','XRS88WSC1LC','Starsys']
            ,['WSX181016-267','Armario de endoscopia','Descripcion de ejemplo','XRS88WSC1LC','Starsys']
            ,['23643776','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643777','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643778','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643779','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643780','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643781','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643782','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643783','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643784','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643785','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643786','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643787','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643789','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643790','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643791','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643792','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['23643793','Bomba Infusión','Descripcion de ejemplo','Volumat MC agilia CL','Fresenius Kabi']
            ,['AF18I085043','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF18I085044','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            ,['AF18I085036','Desfibrilador','Descripcion de ejemplo','Serie R','Zoll']
            
            
        ];*/
        $invReales = [
             ['1','100000001','AF18I085043','1','1','1','1']
            ,['2','100000001','AF18I085043','1','1','1','1']
            ,['3','100000001','AF18I085045','1','1','1','1']
            ,['4','100000001','AF18I085078','1','1','2','1']
            ,['5','100000001','AF18I085089','1','1','1','1']
            ,['6','100000001','AF18I085034','1','1','2','1']
            ,['7','100000001','AF18I085012','1','1','3','1']
        ];
        
        $invReales = array_map(function ($idr) use ($now) {
            return [
                 'serie'            => $idr[0] 
                ,'lote'             => $idr[1]
                ,'serial'           => $idr[2]
                ,'estado'           => ['1','2','3'][array_rand(['1','2','3'],1)]
                ,'tipo'             => $idr[4]
                ,'fecha_ingreso'    => now()
                ,'fecha_baja'       => null
                ,'detalle_id'       => $idr[6]
                ,'unidad_id'        => $idr[5]
                ,'updated_at'       => $now
                ,'created_at'       => $now

            ];
        },$invReales);

        DB::table('inventarios')->insert($invReales);
    }
}
